eks_cluster_public: true
enable_cluster_creator_admin_permissions: false
eks_main_min_size: 1
eks_main_max_size: 3
eks_main_capacity_type: "SPOT"
eks_main_subnets: |
  ["{{ .toutput.vpc.private_subnets[0] }}"]
eks_tools_min_size: 1
eks_tools_max_size: 2
eks_tools_capacity_type: "SPOT"
eks_mon_capacity_type: "SPOT"
eks_mon_subnets: |
  ["{{ .toutput.vpc.private_subnets[0] }}"]
cluster_enabled_log_types: |
  []
